- docker/base/Dockerfile
Adds dependencies for Flux and Swift/T.  Leaving the python dependencies for the PRs that close #5 and #6 under the assumption that they will use pip (or similar) since not all of their dependencies are provided by yum/centos 7.
Closes #3 
Note: this image has been built and pushed to docker hub as exaworks/sdk-base:latest
> docker: add Dockerfile for base image

- .github/workflows/ci_rp.yml
- docker/base/Dockerfile
- docker/flux/Dockerfile
- docker/flux/test.sh
Builds on top of #16.  It was only after trying to compile Flux that I realized the `python36-cffi` package is only in EPEL.  So this PR adds EPEL before installing all of the dependency packages.  Otherwise, the previous `RUN` commands from #16 should be the same.
This PR ensures that flux is built correctly by running `make check` as part of the image build.  It also adds a small test.sh that ensures flux starts and can run a simple single-core job.
While the Dockerfile is technically parameterized to support different versions of flux-core, I only tested that the latest release (0.24.0) builds and runs successfully.
Closes #4
> Add flux dockerfile

- .github/workflows/deploy.yml
Cleanup the deploy workflow to be more debuggable and maintainable (drop lots of fancy, unnecessary caching).
Fix the broken dockerfile path reference.
> ci: simplify deploy workflow action

- .github/workflows/deploy.yml
Setup the deploy workflow to build the 4 components into a single image a deploy to docker hub.  Useful for testing the psi-j-python repo (among other things).
I went ahead and deployed the image as `exaworks/sdk`.  Thoughts on the name?
Closes #47
> CI: deploy combined image

- .github/workflows/ci.yml
Problem: the flux validator does not allow merge commits which puts the
PR into a deadlock when the merge fallback action is applied by mergify
> ci: switch to using an exaworks-specific validator

- docker/base/Dockerfile
Problem: whenever a new patch version of ant is released, they remove the old versions from the mirrors.
Solution: Use the archive so that we can reliably pull our pinned version of ant.
> base: switch to using apache archive for ant

- .github/workflows/deploy.yml
- docker/base/scripts/install-mpi.sh
It is hard to test the `deploy` action since it only runs after a PR merge. So a failure occurred with a message:
```
Run docker push exaworks/sdk-base:latest
The push refers to repository [docker.io/exaworks/sdk-base]
tag does not exist: exaworks/sdk-base:latest
Error: Process completed with exit code 1.
```
This includes a fix for that error by tagging the already built centos7 images with the `latest` tag before pushing.
Also includes a fix for some error messages that I was seeing in the building of the centos8 image in CI
> CI: Fix deploy of the `latest` tag

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- docker/base/scripts/install-mpi.sh
- docker/base/scripts/install-python.sh
- docker/base/ubuntu2004/Dockerfile
- docker/rp/run_rp_test.sh
- docker/swift-t/install-deps.sh
- docker/swift-t/install-swift-t.sh
Issues to resolve:
- edited on 09/17: keep this for future PR (see ticket [#74](https://github.com/ExaWorks/SDK/issues/74))
```
=> ERROR [5/8] RUN ./install-deps.sh                                                                                                                                                                                                                              0.2s
------                                                                                                                                                                                                                                                                  
> [5/8] RUN ./install-deps.sh:
#9 0.225 ./install-deps.sh: 14: Syntax error: Bad fd number
------
executor failed running [/bin/sh -c …
```
> base: introduced docker file for Ubuntu 20.04

- .gitlab-ci.yml
- ci/config/llnl/config.yaml
- ci/config/llnl/packages.yaml
- ci/tests/flux/test.sh
- ci/tests/parsl-flux/test.sh
- ci/tests/parsl/test.py
- ci/tests/parsl/test.sh
- ci/tests/rp-flux/resource_flux.json
- ci/tests/rp-flux/test.sh
- ci/tests/rp/test.sh
- ci/tests/swift-t/test.sh
This PR adds in bare metal CI tests for gitlab. These tests utilize Spack to build the SDK and come in the form of 3 new jobs added into the CI pipeline. 
The first stage uses Spack to build the SDK. This build process is aided with a couple configuration files. `config.yaml` is essentially a copy of the default Spack configuration except that the field for `url_fetch_method` is set to `curl` instead of the default of `urllib`. This change was made because the default option seemed to result in some intermittent timeout failures when tested on LLNL machines. `packages.yaml` contains information on some of the SDK dependencies and where they can already be found on the machine running the build. This configuration will likely be site or machine specific. In this PR both configuration files …
> Add in bare metal tests for Gitlab CI

- .mergify.yml
This PR seeks to fix the configuration for mergify. According to [this post ](https://blog.mergify.com/strict-mode-deprecation/), strict mode for mergify is now deprecated, and there is a new way to go about queuing merge requests. This PR follows most of the recommendations from the blog post. In addition, because our test matrix is large and growing, it made sense to make use of anchors so as not to repeat the list of CI tests under both the queue_rules and pull_request_rules. Because using anchors and aliases can be a bit tricky with arrays, I used the `and` operator as described [here](https://docs.mergify.com/conditions/#combining-conditions-with-operators).
> ci: updated mergify config away from deprecated 'strict' mode

- .github/test.py
- .github/workflows/ci.yml
This PR includes changes that upload the testing results to the [sdk testing dashboard](https://sdk.testing.exaworks.org/). 
This functionality mainly exists in a new `test.py` file that is used as a wrapper script to run the tests and capture and upload the results to the testing dashboard. For the SDK, we are curating a limited scope of data in hopes that we can get approval to upload results from computing centers like LLNL. The limited scope includes information like build parameters, results, and the output from running the tests themselves. 
Currently the build of the docker containers does not send any results to the dashboard, should we include each build as a test as well? For example, a run in this case would be the entire SDK build, and the tests would be SDK component build.
> Upload ci results to testing dashboard

- .github/test.py
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
This PR introduces changes to add a scheduled CI workflow to run tests on all builds for SDK images. The schedule runs on a daily basis and uploads results to the SDK testing dashboard https://sdk.testing.exaworks.org/summary.html. Because the results are uploaded to the dashboard, failing tests do not trigger a failing pipeline and should not be interpreted as such. These tests test the images deployed on Docker Hub rather than building fresh containers from source.
Because we are using the containers from docker hub, it was identified that the docker hub containers are not built with the integration docker file, so the integration was added to the deployment pipeline. Because we now use the integration dockerfile as the last stage of the build, the default command of the SDK image is …
> CI: Add scheduled tests to workflow 

- ci/tests/rp/test.sh
Enforce to create VE within the runner environment (agent's VE supports `venv` or `conda`)
> ci-rp: create VE within runner environment

- docker/tutorials/Dockerfile
- docker/tutorials/README.md
- docker/tutorials/push-multi-platform.sh
Container building fails on ARM platform (e.g., mac M1/2) due to platform limitation of some packages, thus we use a specific platform to build the container and target multiple platforms (`linux/amd64`,`linux/arm64`)
> Build tutorials docker container for `linux/amd64`,`linux/arm64` platforms

- docker/tutorials/Dockerfile
- docker/tutorials/README.md
Environment for Parsl got to be separated due to dependencies
Whenever notebook is started, user need to pick a kernel/environment, currently 2 envs are provided: `parsl` and `root` (which is a base conda env)
(*) was tested successfully with all tutorials (for Parsl only the first tutorial was tested)
(**) corresponding `sdk-tutorials` container image is pushed to [DockerHub](https://hub.docker.com/r/exaworks/sdk-tutorials/tags)
> tutorials: fixed environment

- .mergify.yml
`Mergify will always report errors in the future if a rebase merge is impossible`
based on this comment: https://github.com/ExaWorks/SDK/pull/173#issuecomment-1494539359
> mergify: drop parameter `rebase_fallback`

- ci/tests/test.py
Found a fix for the error  mentioned in https://github.com/ExaWorks/SDK/issues/181 in the following Stackoverflow thread: 
https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled/72374542#72374542:~:text=Complete%20code%20snippets,method%20for%20reuse%3A
> Added class to initialize legacy session to fix Conda post request error

- .github/ISSUE_TEMPLATE/ci_request.md
Documentation uses `description`, but it is actually `about`
> ci-request: fixed attribute `about`

- ci/tests/smartsim/test.py
- ci/tests/smartsim/test.sh
Add a simple SmartSim experiment to use as a smoke test.
This experiment will launch an orchestrator. It will then attempt to store a tensor on the orchestrator at some key, and then retrieve the tensor stored at the same key.
If any of the ML backends (TF, Torch, ONNX) are installed, then for each backend, the test script will also create a simple ML model, store it on the orchestrator, and run the model with dummy a input tensor, and retrieve the output tensor.
> SmartSim Smoke Tests

- .gitlab/llnl-ci-spack.yml
This is a small PR that will wipe the spack directory to rebuild spack from scratch every (for now) 5 days.
> LLNL spack CI wipe

- .gitlab/conda-requirements-ppc64le.yml
- .gitlab/llnl-ci-conda.yml
Enabling conda tests on `ppc64le` machine Lassen. The `conda-requirements-ppc64le.yml` was added in [PR 209](https://github.com/ExaWorks/SDK/pull/209)
> Added lassen machine, reqs point to conda-requirements-ppc64le.yml

- .gitlab/README.md
- .gitlab/llnl-ci-spack.yml
When installing Swift-T via `spack`, its spack installed `ant` dependency fails to initialize the Java VM. We're now instructing spack to use the ant installation already available on LLNL machines.
> LLNL CI Spack: added Ant fix for swift-t installation

- ci/tests/rp-flux/test.sh
- ci/tests/rp/test.sh
to eliminate stuff like below when manually running tests, where >1 rp.session... dir accumulates:
```
...
--- smoke test 0
rm: cannot remove '/global/homes/c/cowan/radical.pilot.sandbox/rp.session.nid005974.cowan.019684.0000'$'\n''rp.session.nid005916.cowan.019684.0001'$'\n''rp.session.nid004876.cowan.019684.0002'$'\n''rp.session.nid200241.cowan.019690.0000'$'\n''rp.session.nid200241.cowan.019690.0001'$'\n''rp.session.nid200002.cowan.019690.0002'$'\n''rp.session.nid200002.cowan.019690.0003'$'\n''rp.session.nid200044.cowan.019
692.0000'$'\n''rp.session.nid200044.cowan.019692.0001'$'\n''rp.session.nid200023.cowan.019692.0002'$'\n''rp.session.nid200023.cowan.019692.0003': File name too long
--- cleaned pilot sandbox
Success!
...
```
still fragile, but slightly better...
> rp tests: slightly improve pilot sandbox cleanup robustness
